apiVersion: v1
kind: Service
metadata:
  name: loan-backend
  namespace: fractal-capstone
  labels:
    app: loan-backend
spec:
  type: ClusterIP
  selector:
    app: loan-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
