apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-blue-config
  namespace: fractal-capstone
data:
  # this file will be mounted at /usr/share/nginx/html/color/index.html
  color: "blue"
  index.html: "blue"
  BACKEND_BASE_URL: "http://loan-backend:8080"
